name: MCOC Store Automation 1

on:
  schedule:
    - cron: '0 8 * * *'  # runs daily at 8:00 AM UTC
  workflow_dispatch:       # also allows manual trigger from GitHub UI

jobs:
  run-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fix playwright permissions
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright browsers
        run: ./node_modules/.bin/playwright install chromium --with-deps

      # - name: Install Playwright browsers
      #   # run: node node_modules/.bin/playwright install chromium --with-deps
      #   run: ./node_modules/.bin/playwright install chromium --with-deps

      - name: Write credentials and config from secrets
        run: |
          echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
          echo '${{ secrets.CONFIG_JSON }}' > config.json

      - name: Run store script
        run: node login3.js

      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: '*.png'